### ISSUE TITLE
"/plan" route giving "Internal Server Error" (code 500)

### ISSUE THREAD

**Issue by adeemjassani** [konveyor/tackle-container-advisor#127]
I have set up the TCA service on a remote server and on testing the service, found that the "/health_check" and "/assess" routes are succeeding with code 200 but the "/plan" route is failing with error code 500. Can someone point me to the likely cause and solution of this error?

**Comment by adeemjassani** [comment]
Found the cause:
In the "service/routes.py" file, the "/plan" route calls the "do_planning" function from the "service/functions.py" file but there is a typo in this file as the function is named "do_plan" instead

**Comment by mmerler** [comment]
Thank you for finding this bug! You were right, we just pushed the function renaming and it will work now. Please let us know if this fixes your problem.
