### ISSUE TITLE
containerize endpoint for operators possibly defaults to baseos images

### ISSUE THREAD

**Issue by mihirc-github** [konveyor/tackle-container-advisor#155]
svc: uCloud Multitenant Core Platform for VMware returns {'Red Hat Enterprise Linux': 'https://hub.docker.com/r/roboxes/rhel7'}

**Comment by mmerler** [comment]
Part of a more general refactor of Containerize endpoint specific for operators. Pending clear definition of operators usecase

**Comment by mmerler** [comment]
done
