### ISSUE TITLE
Requiring inputs on couple of things

### ISSUE THREAD

**Issue by dipjyotighosh** [konveyor/tackle-container-advisor#54]
Dear Team, 

1) What would be expected for technology summary here as it seems to unable to create an output?
2) How to upload bulk files onto the page? Here I can see only one input is allowed

Input : -
[
  {
    "application_name": "Sample",
    "application_description": "This is a Sample App",
    "component_name": "Framework",
    "operating_system": "RHEL",
    "programming_languages": "Java",
    "middleware": "Kafka",
    "database": "PostGreSQL",
    "integration_services_and_additional_softwares": "",
    "technology_summary": "Web"
  }
]

Output  : -
{
  "status": 201,
  "message": "Assessment completed successfully!",
  "assessment": [
    {
      "Name": "Sample",
      "Desc": "This is a Sample App",
      "Cmpt": "Framework",
      "OS": "{'RHEL': {'Linux|Red Hat Enterprise Linux': ''}}",
      "Lang": "{'Java': {'Java': ''}}",
      "App Server": "{}",
      "Dependent Apps": "{'Kafka': {'Apache Kafka': ''}, 'PostGreSQL': {'PostgreSQL': ''}}",
      "Runtime": "{}",
      "Libs": "{}",
      "Reason": "Reason 101: Medium or low confidence for the inferred data: {\"Web\": {\"Java|Java Web Start\": \"\", \"Apache HTTP Server\": \"\", \"Java|Google Web Toolkit (GWT)\": \"\"}}",
      "KG Version": "1.0.0"
    }
  ]
}

**Comment by kaliaanup** [comment]
Hi @dipjyotighosh 

Thanks for using TCA.
1. technology summary: several times we have observed that clients may not have inputs mapped to specific columns like OS, Database, middleware and so on. In such cases clients can provide everything under the technology summary. For example in your case you can provide everything as follows.

Input : -
[
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "RHEL, Java, Kafka, Web, PostGreSQL"
}
]

2. Yes you can upload bulk input. Note that API consumes an array list. For example, I can divide your previous inputs into multiple components and add information as follows.

[
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "RHEL"
},
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "Java"
},
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "Kafka"
},
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "PostGreSQL"
},
{
"application_name": "Sample",
"application_description": "This is a Sample App",
"component_name": "Framework",
"operating_system": "",
"programming_languages": "",
"middleware": "",
"database": "",
"integration_services_and_additional_softwares": "",
"technology_summary": "Web"
}
]

Please let me know if it resolves your concerns and I can close the issue.

**Comment by dipjyotighosh** [comment]
Thanks Anup. You may close this one.
