### ISSUE TITLE
Create a framework for knowledge augmentation

### ISSUE THREAD

**Issue by kaliaanup** [konveyor/tackle-container-advisor#84]
We need to create a framework to add entities and the other aspects such as mentions, relations, docker images, openshift images, operators and versions.

**Comment by mmerler** [comment]
The framework must support the following functionalities:
1. allow a user to programmatically update any table of choice
2. allow a user to add applications directly
3. allow for single entry or batch updates
4. perform checks on the entries that the user is trying to upload (duplicates, format, inconsistencies, etc.)
5. automatically check if any other related tables/modules need to be updated as a consequence of the new insertion, and perform those updates
For example, when a new item is added to the Entities Table, the system must 
   5.1	look for additional entity mentions (from wikidata, etc.), and update the Entity Mentions Table
   5.2	establish possible Entity Relationships
   5.3	trigger the re-training of the Entity Standardization Model

**Comment by mmerler** [comment]
This issue is connected to issue #47
