### ISSUE TITLE
Add Vagrant and VirtualBox support for development environments

### ISSUE THREAD

**Issue by rofrano** [konveyor/tackle-container-advisor#96]
In order to provide several options for creating a repeatable development environment, we should over using Vagrant and VirtualBox as a solution so that developers can use whatever IDE they'd like.

You can read more about creating these environments in the article: [Creating Reproducable Development Environments](https://johnrofrano.medium.com/creating-reproducible-development-environments-fac8d6471f35)

**Comment by lamwassi** [comment]
Great this Solution is needed to deal with dev  environment issues .
