### ISSUE TITLE
Deploy TCA Docker image to Quay.io

### ISSUE THREAD

**Issue by rofrano** [konveyor/tackle-container-advisor#99]
**As a** User of TCA. 
**I need** a way to run TCA without having to build my own Docker image 
**So that** I don't need to create a proper Python 3.8 development environment

#### Assumptions

- Not everyone who wants to use TCA is going to have a Python 3.8 development environment with sqllite to build the needed knowledge graphs
- The recent problems we had with #94 **Unable to connect to Database** would have been avoided if we supplied a pre-built image 
- Other Konveyor projects make their tools available on the `quay.io/konveyor` Docker registry
- If we push our Docker image to quay.io then users will not have to build them
- Recommend we call the image: `quay.io/konveyor/tackle-container-advisor` 

#### Acceptance Criteria

```gherkin
Given  the TCA Docker image is available on quay.io
When I use the command: `docker run -d -p 8000:8000 quay.io/konveyor/tackle-container-advisor`
Then I will have TCA running on my `localhost` at port `8000`
```

**Comment by mmerler** [comment]
completed
